---
stages:
- sync
- test
- secret-detection
- validate
- deploy

variables:
  SECRET_DETECTION_ENABLED: 'true'

include:
- template: Security/Secret-Detection.gitlab-ci.yml

secret_detection:
  stage: secret-detection

.base_databricks:
  image: python:3.10-slim
  before_script:
    # Install Linux dependencies required by Homebrew
    - apt-get update && apt-get install -y build-essential curl file git
    # Install Homebrew (Linuxbrew)
    - /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    # Add Homebrew to PATH
    - echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> ~/.bashrc
    - eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
    # Install databricks-cli via brew
    - brew tap databricks/tap
    - brew install databricks
    - |
      # Optional: add databricks completions (bash)
      if [ -f "$(brew --prefix)/etc/bash_completion.d/databricks" ]; then
          echo "source $(brew --prefix)/etc/bash_completion.d/databricks" >> ~/.bashrc
          source $(brew --prefix)/etc/bash_completion.d/databricks
      fi
    # Verify installation
    - databricks --version

databricks_bundle_validate:
  extends: .base_databricks
  stage: validate
  script:
    - databricks bundle validate
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always

databricks_bundle_deploy:
  extends: .base_databricks
  stage: deploy
  script:
    - databricks bundle deploy
  rules:
    - when: manual

mirror_to_github:
  stage: sync
  script:
    - git config --global user.email "m4data@auto.com"
    - git config --global user.name "GitLab CI"
    - GITLAB_SOURCE_USERNAME=${GITLAB_SOURCE_USERNAME::-1}
    - GITHUB_USERNAME=${GITHUB_USERNAME::-1}
    - git clone https://$GITLAB_SOURCE_USERNAME:$GITLAB_SOURCE_PAT@gitlab.com/databricks_tests1/stocks_tracking-dbks-dbt.git
    - cd stocks_tracking-dbks-dbt
    - git remote add github https://$GITHUB_USERNAME:$GITHUB_PAT@github.com/m4DataS/stocks_tracking-dbks-dbt.git
    - git branch -a
    # Push all branches
    - git push github --all --force
    # Push tags too (optional)
    - git push github --tags --force
  only:
    - schedules
    - feature/ingestion_yahoof
